import { Attraction } from 'types/attraction';

export const testItems: Attraction[] = [
  {
    id: 'Q1473348',
    image_path: ['images/Q1473348.webp', 'images/Q1473348_1.webp'],
    name: 'Glasgow Cathedral',
    parentTypeLabel: 'history_culture,architecture,topspot',
    typeLabel: 'cathedral, tourist attraction, Scottish civil parish',
    latitude: 55.8631,
    longtitude: -4.2346,
    wikipedia: 'https://en.wikipedia.org/wiki/Glasgow_Cathedral',
    summary:
      "Glasgow Cathedral (Scottish Gaelic: Cathair-eaglais Ghlaschu) is a parish church of the Church of Scotland in Glasgow, Scotland. It was the cathedral church  of the Archbishop of Glasgow, and the mother church of the Archdiocese of Glasgow and the province of Glasgow, from the 12th century until the Scottish Reformation in the 16th century. It is the oldest cathedral in mainland Scotland and the oldest building in Glasgow. With St Magnus Cathedral in Orkney, they are the only medieval cathedrals in Scotland to have survived the Reformation virtually intact. The medieval Bishop's Castle stood to the west of the cathedral until 1789.  Although notionally it lies within the Townhead area of the city, the Cathedral grounds and the neighbouring Necropolis are considered to be their own district within the city.\nThe cathedral is dedicated to Saint Mungo (also known as Kentigern), the patron saint of Glasgow, whose tomb lies at the centre of the building's Lower Church. The first stone cathedral was dedicated in 1136, in the presence of David I. Fragments of this building have been found beneath the structure of the present cathedral, which was dedicated in 1197, although much of the present cathedral dates from a major rebuilding in the 13th century. Following its foundation in 1451, the University of Glasgow held its first classes within the cathedral's chapter house. After the Reformation, Glasgow Cathedral was internally partitioned to serve three separate congregations (Inner High, Outer High and Barony). The early 19th century saw a growing appreciation of the cathedral's medieval architecture, and by 1835 both the Outer High and Barony congregations had moved elsewhere in the city, allowing the restoration of the cathedral to something approaching its former glory.\n\nGlasgow Cathedral has been Crown property since 1587. The entire cathedral building passed into the care of the state in 1857, and today it is the responsibility of Historic Environment Scotland. The congregation is today part of the Church of Scotland's Presbytery of Glasgow.",
    county: 'Glasgow City',
    region: 'Scotland',
    country: 'Scotland',
  },
  {
    id: 'Q619558',
    image_path: ['images/Q619558.webp'],
    name: 'Portman Road',
    parentTypeLabel: 'sports,topspot',
    typeLabel: 'association football venue, all-seater stadium, tourist attraction',
    latitude: 52.055,
    longtitude: 1.145277777,
    wikipedia: 'https://en.wikipedia.org/wiki/Portman_Road',
    summary:
      "Portman Road is a football stadium in Ipswich, Suffolk, England, which has been the home ground of Ipswich Town since 1884. The stadium has also hosted many England youth international matches, and one senior England friendly international match, against Croatia in 2003. It staged several other sporting events, including athletics meetings and international hockey matches, musical concerts and Christian events.\nIpswich Town moved to the ground in 1884. The stadium recorded its highest attendance in March 1975, when 38,010 fans attended a match against Leeds United. Its four stands were converted to all-seater in the early 1990s following the recommendations of the Taylor Report. The stadium underwent significant redevelopments in the early 2000s, which increased the capacity from 22,600 to 30,311, making it the largest-capacity football ground in East Anglia. Once the Gamechanger 20 Ltd takeover in 2021 was completed, the club invested heavily in the stadium to bring it more up to date after years of neglect from the previous ownership. This included new dugouts, undersoil heating and a new hybrid pitch which slightly reduced the overall attendance to 29,673. After the club's promotion back to the Premier League in 2024, the club had to invest heavily again into the stadium to bring it up to the Premier League’s standards. This included over 100 projects ranging from new press and camera areas to increasing the away supporter allocation. Once these upgrades were completed, this increased the overall capacity to the current figure of 30,056.",
    county: 'Suffolk',
    region: 'East of England',
    country: 'England',
  },
  {
    id: 'Q301338',
    image_path: ['images/Q301338.webp'],
    name: 'Stourhead',
    parentTypeLabel: 'natural,topspot',
    typeLabel: 'historic house, tourist attraction, English garden, estate',
    latitude: 51.106111111,
    longtitude: -2.317777777,
    wikipedia: 'https://en.wikipedia.org/wiki/Stourhead',
    summary:
      'Stourhead () is a 1,072-hectare (2,650-acre) estate at the source of the River Stour in the southwest of the English county of Wiltshire, extending into Somerset.\nThe estate is about 4 km (2+1⁄2 mi) northwest of the town of Mere and includes a Grade I listed 18th-century Neo-Palladian mansion, the village of Stourton, one of the most famous gardens in the English landscape garden style, farmland, and woodland. Stourhead has been part-owned by the National Trust since 1946.',
    county: 'Wiltshire',
    region: 'South West',
    country: 'England',
  },
  {
    id: 'Q3533344',
    image_path: ['images/Q3533344.webp', 'images/Q3533344_1.webp'],
    name: 'Glasgow Tower',
    parentTypeLabel: 'topspot',
    typeLabel: 'observation tower',
    latitude: 55.8585,
    longtitude: -4.29325,
    wikipedia: 'https://en.wikipedia.org/wiki/Glasgow_Tower',
    summary:
      'Glasgow Tower (formerly known as the Millennium Tower) is a 127 metres (417 ft) free-standing landmark observation tower located on the south bank of the River Clyde in Glasgow, Scotland, and is part of the Glasgow Science Centre complex. It holds a Guinness World Record for being the tallest fully rotating freestanding structure in the world, in which the whole structure is capable of rotating 360 degrees. \nThe Glasgow Tower is currently the tallest building in Glasgow and Scotland, and has held these records since its completion in 2001. It was designed by architect Richard Horden in 1992 and was initially proposed as a landmark for the city, with a proposal to build the tower in city\'s St Enoch Square. It was later decided that, due to its "unique design", it would be constructed to accompany the Glasgow Science Centre complex instead.',
    county: 'Glasgow City',
    region: 'Scotland',
    country: 'Scotland',
  },
  {
    id: 'Q23308',
    image_path: ['images/Q23308.webp'],
    name: 'British Library',
    parentTypeLabel: 'topspot',
    typeLabel:
      'universal library, library building, national library, non-departmental public body, tourist attraction, reference library, research library',
    latitude: 51.529444,
    longtitude: -0.126944,
    wikipedia: 'https://en.wikipedia.org/wiki/British_Library',
    summary:
      'The British Library is the national library of the United Kingdom. Based in London, it is the largest library in the world, with an estimated collection of over 200 million items from multiple countries. As a legal deposit library, it receives copies of all books produced in the United Kingdom and Ireland, as well as a significant proportion of overseas titles distributed in the United Kingdom. The library operates as a non-departmental public body sponsored by the Department for Culture, Media and Sport.\nThe British Library is a major research library, with items in many languages and in many formats, both print and digital: books, manuscripts, journals, newspapers, magazines, sound and music recordings, videos, play-scripts, patents, databases, maps, stamps, prints, drawings. The Library\'s collections include around 14 million books, along with substantial holdings of manuscripts and items dating as far back as 2000 BC. The library maintains a programme for content acquisition and adds some three million items each year occupying 9.6 kilometres (6 mi) of new shelf space.\nThe Library\'s purpose-built building stands next to St Pancras station in London. It was officially opened by Elizabeth II on 25 June 1998, and is classified as a Grade I listed building "of exceptional interest" for its architecture and history. Off-site storage is provided at a second site near Boston Spa in Yorkshire.',
    county: 'London',
    region: 'London',
    country: 'England',
  },
  {
    id: 'Q5600230',
    image_path: ['images/Q5600230.webp'],
    name: 'Great Whipsnade Railway',
    parentTypeLabel: 'topspot',
    typeLabel: 'narrow-gauge railway, tourist attraction',
    latitude: 51.849,
    longtitude: -0.545,
    wikipedia: 'https://en.wikipedia.org/wiki/Great_Whipsnade_Railway',
    summary:
      'The Great Whipsnade Railway, also known as The Jumbo Express, is an English, 2 ft 6 in (762 mm) narrow gauge heritage railway that operates within ZSL Whipsnade Zoo in Bedfordshire, England.',
    county: 'Central Bedfordshire',
    region: 'East of England',
    country: 'England',
  },
  {
    id: 'Q102328757',
    image_path: ['images/Q102328757.webp'],
    name: "St Lawrence's Church, Longridge",
    parentTypeLabel: 'topspot',
    typeLabel: 'parish church, tourist attraction, Anglican church building',
    latitude: 53.8253,
    longtitude: -2.601,
    wikipedia: 'https://en.wikipedia.org/wiki/St_Lawrence%27s_Church,_Longridge',
    summary:
      "St Lawrence's Church, located on Chapel Hill in Longridge, Lancashire, England, is an active Anglican parish church in the diocese of Blackburn. Built as a chapel of ease of St Wilfrid, Ribchester in the early 16th century, it was made a parish church in 1868, a role it now shares, jointly, with the nearby St Paul's Church.",
    county: 'Lancashire',
    region: 'North West',
    country: 'England',
  },
  {
    id: 'Q7598687',
    image_path: ['images/Q7598687.webp'],
    name: 'Stanedge Pole',
    parentTypeLabel: 'history_culture,architecture,topspot',
    typeLabel: 'architectural landmark, boundary marker',
    latitude: 53.3561,
    longtitude: -1.6306,
    wikipedia: 'https://en.wikipedia.org/wiki/Stanedge_Pole',
    summary:
      'Stanedge Pole also known as Stanage Pole (grid reference SK2468784429) is a landmark on Hallam Moors close to Stanage Edge in South Yorkshire, England. Standing at a height of 438 metres (1,437 feet),  it marks the border between Derbyshire and South Yorkshire and can be seen for several miles around.\nA pole has stood on the site since at least 1550. Many initials have been carved into the rock that supports it, and five can be identified as initials of the parish road surveyors who renewed the pole when needed. "T.C. 1550", "H.W. 1581", "T.M. 1631", "H.H. 1697" and "F.N. 1740" are the marks of the parish surveyors and the date the pole was renewed. The pole is a way marker on a medieval packhorse road known as the Long Causeway or Long Causey which runs west from Sheffield.  It was used for centuries as a boundary marker between the parishes of Sheffield, Hathersage and Ecclesfield. Although it is widely believed the Long Causeway follows the line of a Roman road that ran from Templeborough Roman fort to the fort at Navio (Brough-on-Noe), archaeologists have cast doubt on this. There is some suggestion that the pole also marks the old boundary between Mercia and Northumberland.\nThe top part of the pole was removed on Friday, 27 February 2015. A spokesperson for the Peak District National Park explained that "the wood on the top half of the pole was rotten and therefore a health and safety risk to the public. We had no choice but to make the pole safe by cutting off the top part.” \n\nOn 17 April 2016 a group of people with an interest in the pole and surrounding environment, including the Peak District National Park Authority and the British Mountaineering Council, erected a new pole at the site to mark the 65th anniversary of the creation of the Peak District National Park. Support for the renewal also came from the Hope Cement Works, The Durham Foundry (Sheffield) Ltd, The Cutler\'s Company, Sheffield Clarion Ramblers and some public subscriptions. The new pole is formed from a locally felled larch tree, with a frame made by Hope Cement Works, and a base cast in Sheffield. The  base is cast from ductile iron and has information cast into it (see photograph).\n\n\n== References ==',
    county: 'Derbyshire',
    region: 'East Midlands',
    country: 'England',
  },
  {
    id: 'Q57357',
    image_path: ['images/Q57357.webp'],
    name: "Hadrian's Wall",
    parentTypeLabel: 'topspot',
    typeLabel:
      'international border, Roman limes, Roman archaeological site, cordon, tourist attraction',
    latitude: 55.024166666,
    longtitude: -2.2925,
    wikipedia: 'https://en.wikipedia.org/wiki/Hadrian%27s_Wall',
    summary:
      "Hadrian's Wall (Latin: Vallum Hadriani; also known as the Roman Wall, Picts' Wall, or Vallum Aelium in Latin) is a former defensive fortification of the Roman province of Britannia, begun in AD 122 in the reign of the Emperor Hadrian. Running from Wallsend on the River Tyne in the east to Bowness-on-Solway in the west of what is now northern England, it was a stone wall with large ditches in front and behind, stretching across the whole width of the island. Soldiers were garrisoned along the line of the wall in large forts, smaller milecastles, and intervening turrets. In addition to the wall's defensive military role, its gates may have been customs posts.\nHadrian's Wall Path generally runs close along the wall. Almost all the standing masonry of the wall was removed in early modern times and used for local roads and farmhouses. None of it stands to its original height, but modern work has exposed much of the footings, and some segments display a few courses of modern masonry reconstruction. Many of the excavated forts on or near the wall are open to the public, and various nearby museums present its history. The largest Roman archaeological feature in Britain, it runs a total of 73 miles (117.5 kilometres). Regarded as a British cultural icon, Hadrian's Wall is one of Britain's major ancient tourist attractions. It was designated a UNESCO World Heritage Site in 1987. The turf-built Antonine Wall of AD 142 in what is now central Scotland, which briefly superseded Hadrian's Wall before being abandoned, was declared a World Heritage Site in 2008.\nHadrian's Wall lies entirely within England and has never formed the Anglo-Scottish border, though it is sometimes loosely or colloquially described as such.",
    county: 'Northumberland',
    region: 'North East',
    country: 'England',
  },
  {
    id: 'Q39671',
    image_path: ['images/Q39671.webp'],
    name: 'Stonehenge',
    parentTypeLabel: 'history_culture,architecture,topspot',
    typeLabel: 'archaeological site, monument, cromlech, tourist attraction, history museum, henge',
    latitude: 51.178888888,
    longtitude: -1.826111111,
    wikipedia: 'https://en.wikipedia.org/wiki/Stonehenge',
    summary:
      "Stonehenge is a prehistoric megalithic structure on Salisbury Plain in Wiltshire, England, two miles (3 km) west of Amesbury. It consists of an outer ring of vertical sarsen standing stones, each around 13 feet (4.0 m) high, seven feet (2.1 m) wide, and weighing around 25 tons, topped by connecting horizontal lintel stones, held in place with mortise and tenon joints, a feature unique among contemporary monuments.  Inside is a ring of smaller bluestones. Inside these are free-standing trilithons, two bulkier vertical sarsens joined by one lintel. The whole monument, now in ruins, is aligned towards the sunrise on the summer solstice and sunset on the winter solstice. The stones are set within earthworks in the middle of the densest complex of Neolithic and Bronze Age monuments in England, including several hundred tumuli (burial mounds).\nStonehenge was constructed in several phases beginning about 3100 BC and continuing until about 1600 BC. The famous circle of large sarsen stones were placed between 2600 BC and 2400 BC. The surrounding circular earth bank and ditch, which constitute the earliest phase of the monument, have been dated to about 3100 BC. Radiocarbon dating suggests that the bluestones were given their current positions between 2400 and 2200 BC, although they may have been at the site as early as 3000 BC.\nOne of the most famous landmarks in the United Kingdom, Stonehenge is regarded as a British cultural icon. It has been a legally protected scheduled monument since the Ancient Monuments Protection Act 1882 was passed. The site and its surroundings were added to UNESCO's list of World Heritage Sites in 1986. Stonehenge is owned by the Crown Estate and managed by English Heritage; the surrounding land is owned by the National Trust.\nStonehenge could have been a burial ground from its earliest beginnings. Deposits containing human bone date from as early as 3000 BC, when the ditch and bank were first dug, and continued for at least another 500 years.",
    county: 'Wiltshire',
    region: 'South West',
    country: 'England',
  },
];
