# Generated by Django 6.0.2 on 2026-02-05 10:07

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        VectorExtension()
    ]
