# Generated by Django 6.0.2 on 2026-02-05 10:08

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_enable_vector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('parentTypeLabel', models.CharField(max_length=100)),
                ('typeLabel', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('wikipedia', models.URLField()),
                ('summary', models.TextField()),
                ('image_path', models.JSONField(default=list)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('labelMHE', pgvector.django.vector.VectorField(dimensions=9)),
                ('labelEmbed', pgvector.django.vector.VectorField(dimensions=384)),
                ('summaryEmbed', pgvector.django.vector.VectorField(dimensions=384)),
                ('finalVector', pgvector.django.vector.VectorField(dimensions=777)),
            ],
            options={
                'indexes': [models.Index(fields=['county'], name='idx_county'), models.Index(fields=['region'], name='idx_region'), models.Index(fields=['country'], name='idx_country')],
            },
        ),
    ]
